python project/kaspi_notifications-main/kaspi_notifications/api/urls.py
from django.urls import path

from api.views import UserView

urlpatterns = [
    path('user/', UserView.as_view(), name='user-info'),
]

python project/kaspi_notifications-main/kaspi_notifications/kaspi_notifications/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notifications.urls')),
    path('api/', include('api.urls')),
    path('didar/', include(('logger.urls', 'logger'), namespace='logger')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python project/kaspi_notifications-main/kaspi_notifications/logger/urls.py
from django.conf import settings
from django.urls import path
from logger.views import CabinetLogView, CabinetLogsTable
from django.conf.urls.static import static


urlpatterns = [
    path('cabinetlog/', CabinetLogsTable.as_view(), name='cabinetlog_list'),
    path('cabinetlog/<int:pk>/', CabinetLogView.as_view(), name='cabinetlog_view'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

python project/kaspi_notifications-main/kaspi_notifications/logger/models.py
from django.db import models


class DBLogEntry(models.Model):
    time = models.DateTimeField(auto_now_add=True)
    level = models.CharField(max_length=11)
    message = models.TextField()

    class Meta:
        abstract = True


class GeneralLog(DBLogEntry):
    pass


class CabinetLog(DBLogEntry):
    """
    Cabinet log Model
    """
    STATUS_SUCCESS, STATUS_WARNING, STATUS_ERROR = list(range(1, 4))
    STATUSES = (
        (STATUS_SUCCESS, 'success'),
        (STATUS_WARNING, 'warning'),
        (STATUS_ERROR, 'error')
    )
    id = models.BigAutoField(primary_key=True)
    uid = models.CharField(max_length=32, blank=True, null=True, db_index=True)
    conversation_id = models.CharField(max_length=32, blank=True, null=True)
    cabinet_cookie = models.TextField(blank=True, null=True)
    method = models.CharField(max_length=128, db_index=True)
    merchant_reference = models.CharField(max_length=128, blank=True, null=True, db_index=True)
    status = models.IntegerField(choices=STATUSES, default=STATUS_SUCCESS)
    response_code = models.IntegerField(blank=True, null=True)

    class Meta:
        ordering = ['-pk']
        indexes = [
            models.Index(fields=['time']),
        ]

    def get_db_name(self):
        return self._state.db

python project/kaspi_notifications-main/kaspi_notifications/logger/views.py
import re
import xml
import json
from django.conf import settings
from django.db.models import Q
from django.core.exceptions import PermissionDenied
from django.views.generic.base import View, TemplateView
from django.views.generic import ListView
from pktools.helpers import model_field_exists
from logger.models import CabinetLog


class CabinetLogCommon(View):
    def dispatch(self, request, *args, **kwargs):
        if not (request.user.is_authenticated and request.user.is_superuser):
            raise PermissionDenied()
        return super().dispatch(request, *args, **kwargs)


class CabinetLogsTable(CabinetLogCommon, ListView):
    template_name = 'logger/table.html'
    paginate_by = 20
    default_show_pages = 20
    order_by = '-time'
    search_fields = ['uid', 'merchant_reference']
    search_queries = ['startswith', 'istartswith', 'exact', 'iexact', 'endswith', 'iendswith']

    def get_queryset(self):
        qs = CabinetLog.objects.order_by(self.order_by).defer('message')
        search_conditions = Q()
        for k, v in list(self.request.GET.items()):
            if k == 'q':
                temp_search_fields = self.search_fields
                is_extended_search = False
                search_query = 'exact'
                field_value = v
                prepared_string_array = [x for x in v.split(',') if bool(x)]
                if len(prepared_string_array) and prepared_string_array[-1] in self.search_queries:
                    field_value = ''.join(prepared_string_array[:-1])
                    search_query = prepared_string_array[-1]
                    temp_search_fields.append('method')
                    is_extended_search = True
                for f in temp_search_fields:
                    search_conditions |= Q(**{'%s__exact' % f: v})
                    if is_extended_search:
                        search_conditions |= Q(**{'__'.join([f, search_query]): field_value})
            elif model_field_exists(CabinetLog, k):
                search_conditions &= Q(**{k: v})
            elif k == 'page':
                page = int(v)
                if page >= self.default_show_pages:
                    self.default_show_pages = page + 20

        all_logs = []
        for logger_db_name in settings.LOGGER_DATABASES:
            if search_conditions:
                all_logs.extend(
                    list(
                        qs.filter(
                            search_conditions
                        ).order_by(
                            self.order_by
                        ).using(
                            logger_db_name
                        )[:self.default_show_pages * self.paginate_by]
                    )
                )
            else:
                all_logs.extend(
                    list(
                        qs.order_by(
                            self.order_by
                        ).using(
                            logger_db_name
                        )[:self.default_show_pages * self.paginate_by]
                    )
                )
        all_logs.sort(key=lambda x: -x.time.timestamp())
        return all_logs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['url_params'] = '&' + '&'.join(['%s=%s' % (k, v) for k, v in list(self.request.GET.items()) if k != 'page'])
        context['search_query'] = self.request.GET.get('q', '')
        context['with_tours'] = self.request.GET.get('with_tours')
        context['object_count'] = len(context['object_list'])
        return context


class CabinetLogView(CabinetLogCommon, TemplateView):
    template_name = 'logger/view.html'
    db_name = 'logger'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_log = CabinetLog.objects.using(self.db_name).get(pk=kwargs['pk'])
        logs = []

        for logger_db_name in settings.LOGGER_DATABASES:
            if current_log.uid:
                logs.extend(list(
                    CabinetLog.objects.using(
                        logger_db_name
                    ).filter(
                        uid=current_log.uid
                    ).order_by('pk')))
            elif current_log.conversation_id:
                logs.extend(list(
                    CabinetLog.objects.using(
                        logger_db_name
                    ).filter(
                        conversation_id=current_log.conversation_id
                    ).order_by('pk')))
        for log in logs:
            try:
                message = re.sub(r'>[\n\t\r ]+<', '><', log.message)
                message = xml.dom.minidom.parseString(message.encode('utf-8')).toprettyxml(indent='    ')
            except Exception as e:
                try:
                    message = json.loads(log.message.replace('@', ''))
                    message = json.dumps(message, indent=4, ensure_ascii=False, sort_keys=True)
                except Exception as e:
                    message = log.message
            log.pretty_message = message

        context['current_log'] = current_log
        context['logs'] = logs
        context['logs_count'] = len(logs)
        return context

python project/kaspi_notifications-main/kaspi_notifications/logger/templates/logger/base.html
{% load i18n static %}
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>iRocket | DB logs | {% block title %}{% endblock %}</title>
    <link href={% static "manager/img/favicon.png" %} rel="shortcut icon" type="image/png" />
    <link href={% static "manager/css/bootstrap.min.css" %} rel="stylesheet">
    <link href={% static "manager/font-awesome/css/font-awesome.css" %} rel="stylesheet">

    <!-- Toastr style -->
    <link href={% static "manager/css/plugins/toastr/toastr.min.css" %} rel="stylesheet">

    <!-- Gritter -->
    <link href={% static "manager/js/plugins/gritter/jquery.gritter.css" %} rel="stylesheet">
    <link href={% static "manager/css/plugins/steps/jquery.steps.css" %} rel="stylesheet">
    <link href={% static "manager/css/plugins/datapicker/datepicker3.css" %} rel="stylesheet">
    <link href={% static "manager/css/plugins/datapicker/bootstrap-datetimepicker.css" %} rel="stylesheet">
    <link href={% static "manager/css/animate.css" %} rel="stylesheet">
    <link href={% static "manager/css/plugins/iCheck/custom.css" %} rel="stylesheet">
    <link href={% static "manager/css/plugins/jQueryUI/jquery-ui-1.10.4.custom.min.css" %} rel="stylesheet">
    <link href={% static "manager/css/plugins/jqGrid/ui.jqgrid.css" %} rel="stylesheet">
    <link href={% static "manager/js/plugins/redactor/redactor.css" %} rel="stylesheet">
    <link href={% static "manager/css/manager.css" %} rel="stylesheet">

    {% block css %}
        <style>
            .pace .pace-progress {
                left: 0
            }
        </style>
    {% endblock %}

</head>

<body class="mini-navbar">
<div id="wrapper">
<div id="page-wrapper" class="gray-bg dashbard-1" style="margin: 0">
{% block header %}
<div class="row border-bottom">
    <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <form role="search" class="navbar-form-custom" method="get">
                <div class="form-group">
                    <input type="text" placeholder="Поиск..." class="form-control" name="q" id="top_search" autocomplete="off" value="{{ search_query }}">
                </div>
            </form>
        </div>

        {% block dropdown %}

        {% endblock %}

    </nav>
</div>
{% endblock %}
<div class="row  border-bottom white-bg dashboard-header">
    <div class="col-lg-12">
        <div >
            <ol class="breadcrumb">
                <li>
                    <a href="{% url "logger:cabinetlog_list" %}">Главная</a>
                </li>
                <li>
                    <a href="#">
                        {% block current_breadcrumb %}{% endblock %}
                    </a>
                </li>
            </ol>
            {% block back %}{% endblock %}
        </div>
        <div class="main-{% block content_name %}{% endblock %}">
{#            {% block page_messages %}{% include "manager/includes/page_messages.html" %}{% endblock %}#}
            {% block content %}{% endblock %}

        </div>
    </div>
</div>

</div>

<button class="btn btn-primary btn-circle btn-lg scrollToTop" type="button"><i class="fa fa-chevron-up"></i></button>
</div>

<!-- Mainly scripts -->
<script src={% static "manager/js/jquery-2.1.1.js" %}></script>
<script src={% static "manager/js/bootstrap.min.js" %}></script>
<script src={% static "manager/js/plugins/metisMenu/jquery.metisMenu.js" %}></script>
<script src={% static "manager/js/plugins/slimscroll/jquery.slimscroll.min.js" %}></script>
<script src={% static "manager/js/plugins/typeahead/typeahead.bundle.min.js" %}></script>
<script src={% static "manager/js/plugins/handlebars/handlebars-v3.0.1.js" %}></script>
<script src={% static "manager/js/plugins/toastr/toastr.min.js" %}></script>
<!-- Custom and plugin javascript -->
<script src={% static "manager/js/inspinia.js" %}></script>
<script src={% static "manager/js/plugins/pace/pace.min.js" %}></script>

<!-- jQuery UI -->
<script src={% static "manager/js/plugins/jquery-ui/jquery-ui.min.js" %}></script>

<!-- GITTER -->
<script src={% static "manager/js/plugins/gritter/jquery.gritter.min.js" %}></script>

<!-- Sparkline -->
<script src={% static "manager/js/plugins/sparkline/jquery.sparkline.min.js" %}></script>

<!-- Sparkline demo data  -->
<script src={% static "manager/js/demo/sparkline-demo.js" %}></script>

<!-- jqGrid -->
<script src={% static "manager/js/plugins/jqGrid/i18n/grid.locale-en.js" %}></script>
<script src={% static "manager/js/plugins/jqGrid/jquery.jqGrid.min.js" %}></script>

<!-- iCheck -->
<script src={% static "manager/js/plugins/iCheck/icheck.min.js" %}></script>

<script src={% static "manager/js/plugins/redactor/redactor.min.js" %}></script>
<script src={% static "manager/js/plugins/redactor/ru.js" %}></script>

{#<script src="/static/manager/js/manager-script.js"></script>#}

{% block javascript %}{% endblock %}

</body>
</html>

python project/kaspi_notifications-main/kaspi_notifications/logger/templates/logger/table.html
{% extends 'logger/base.html' %}
{% load admin_list %}

{% block javascript %}
    <script>
    function get_query_dict() {
        var query_dict = {};
        var param_pairs = location.search.substring(1).split('&');
        $.each(param_pairs, function(i, elem){
            if (elem.indexOf('=') == -1)
                return;
            var pair = elem.split('=');
            query_dict[pair[0]] = pair[1];
        });
        return query_dict;
    }

    function construct_url_query(dict) {
        var pairs = [];
        $.each(Object.keys(dict), function(i, elem) {
            pairs.push(elem + '=' + dict[elem]);
        });
        return pairs.join('&');
    }

    $(document).on('click', '.js-filter', function(){
        var query_dict = get_query_dict();
        query_dict[$(this).data('key')] = $(this).data('value');
        if (!$(this).data('value'))
            delete query_dict[$(this).data('key')];
        location.search = construct_url_query(query_dict);
        return false;
    });
    </script>
{% endblock %}

{% block content %}
    <div>
        <a href="#" class="js-filter btn btn-sm" data-key="level" data-value="">Все</a>
        <a href="#" class="js-filter btn btn-sm btn-info" data-key="level" data-value="INFO">Обычные</a>
        <a href="#" class="js-filter btn btn-sm btn-warning" data-key="level" data-value="WARNING">Предупреждения</a>
        <a href="#" class="js-filter btn btn-sm btn-danger" data-key="level" data-value="ERROR">Ошибки</a>
        {% if search_query %}
            <a href="#" class="js-filter btn btn-sm btn btn-default" data-key="level" data-value="DOWNLOAD">Download All {{ object_count }}</a>
        {% endif %}
    </div>
    <br />
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>Время</th>
                <th>Метод</th>
                <th>UID</th>
                <th>Conversation ID</th>
                <th>response code</th>
            </tr>
        </thead>
        {% for log in object_list %}
            <tr class="log {% if log.level == 'WARNING' %}warning{% elif log.level == 'ERROR' %}danger{% endif %}">
                <td><a href="{% url 'logger:cabinetlog_view' pk=log.pk %}?db={{ log.get_db_name }}">{{ log.pk }}</a></td>
                <td>{{ log.time|date:"c" }}</td>
                <td>{{ log.method }}</td>
                <td>{{ log.uid|default:'---' }}</td>
                <td>{{ log.conversation_id|default:'---' }}</td>
                <td>{{ log.response_code }}</td>
            </tr>
        {% endfor %}
    </table>

    {% if is_paginated %}
        <nav>
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li><a href="?page={{page_obj.previous_page_number}}{{ url_params }}">&laquo;</a></li>
                    {% if page_obj.previous_page_number != 1 %}
                        <li><a href="?page=1{{ url_params }}">1</a></li>
                    {% endif %}
                    {% if page_obj.number > 2 %}
                        <li><a>&nbsp;...&nbsp;</a></li>
                    {% endif %}
                    <li><a href="?page={{ page_obj.previous_page_number }}{{ url_params }}">{{ page_obj.previous_page_number }}</a></li>
                {% endif %}

                <li><a href="?page={{ page_obj.number }}{{ url_params }}"><b>{{ page_obj.number }}</b></a></li>

                {% if page_obj.has_next %}
                    {% if page_obj.next_page_number != page_obj.paginator.num_pages %}
                        <li><a href="?page={{ page_obj.next_page_number }}{{ url_params }}">{{ page_obj.next_page_number }}</a></li>
                    {% endif %}
                    {% if page_obj.next_page_number < page_obj.paginator.num_pages|add:"-1" %}
                        <li><a>&nbsp;...&nbsp;</a></li>
                    {% endif %}
                    {% if page_obj.number != page_obj.paginator.num_pages %}
                        <li><a href="?page={{ page_obj.paginator.num_pages }}{{ url_params }}">{{ page_obj.paginator.num_pages }}</a></li>
                    {% endif %}
                    <li><a href="?page={{ page_obj.next_page_number }}{{ url_params }}">&raquo;</a></li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
{% endblock %}

python project/kaspi_notifications-main/kaspi_notifications/logger/templates/logger/view.html
{% extends 'logger/base.html' %}

{% block css %}
    <style>
    pre.error {
        background-color: #F2DEDE;
        border-color: #ebccd1;
        color: #a94442;
    }
    pre.warning {
        color: #8a6d3b;
        background-color: #fcf8e3;
        border-color: #faebcc;
    }
    .display-none {
        display: none;
    }
    .log {
        margin-top: 10px;
        padding: 0 20px;
    }
    .log.current {
        padding: 20px;
        background-color: #d9edf7;
    }
    </style>
{% endblock %}

{% block javascript %}
    <script>
    $(document).on('click', '.js-minimize', function(){
        $(this).removeClass('js-minimize').addClass('js-maximize')
                .text('Развернуть');
        $(this).closest('div.log').find('pre.short-info').slideDown();
        $(this).closest('div.log').find('pre.full-info').slideUp();

        return false;
    });
    $(document).on('click', '.js-maximize', function(){
        $(this).removeClass('js-maximize').addClass('js-minimize')
                .text('Свернуть');
        $(this).closest('div.log').find('pre.short-info').slideUp();
        $(this).closest('div.log').find('pre.full-info').slideDown();

        return false;
    });

        function get_query_dict() {
        var query_dict = {};
        var param_pairs = location.search.substring(1).split('&');
        $.each(param_pairs, function(i, elem){
            if (elem.indexOf('=') == -1)
                return;
            var pair = elem.split('=');
            query_dict[pair[0]] = pair[1];
        });
        return query_dict;
    }

    function construct_url_query(dict) {
        var pairs = [];
        $.each(Object.keys(dict), function(i, elem) {
            pairs.push(elem + '=' + dict[elem]);
        });
        return pairs.join('&');
    }

    $(document).on('click', '.js-download', function(){
        var query_dict = get_query_dict();
        query_dict[$(this).data('key')] = $(this).data('value');
        if (!$(this).data('value'))
            delete query_dict[$(this).data('key')];
        location.search = construct_url_query(query_dict);
        return false;
    });
    </script>
{% endblock %}

{% block current_breadcrumb %}{% if logs.0.uid %}UID: {{ logs.0.uid }}{% else %}Log #{{ pk }}{% endif %}{% endblock %}

{% block content %}
    {% if logs.0.uid %}<h2>UID: {{ logs.0.uid }} &nbsp;
        &nbsp; <a class="js-download btn btn-sm btn btn-default" data-key="level" data-value="all" id="download">Download All {{ logs_count }}</a></h2><br />
    {% endif %}
    {% for log in logs %}
        <div class="log {% if log.pk == current_log.pk %}current{% endif %}">
            <div>
                <span class="label label-success">{{ log.method }}</span>
                <span class="label label-success">{{ log.time|date:"c" }}</span>
                <a href="#" class="btn btn-xs btn-warning js-maximize">Развернуть</a>
                <span class="label label-info">{{ log.conversation_id }}</span>
                <span class="label label-info">{{ log.response_code }}</span>
                <span class="label label-info">{{ log.booking_reference }}</span>
                <a class="js-download btn btn-xs btn-default" data-key="level" data-value="{{log.pk}}">Download</a>
            </div>

            <pre class="{{ log.level.lower }} short-info">{{ log.pretty_message|truncatechars:100 }}</pre>
<pre class="{{ log.level.lower }} display-none full-info">
URL: {{ log.url }}
COOKIE: {{ log.cabinet_cookie }}

{{ log.pretty_message }}
</pre>
        </div>
    {% endfor %}
{% endblock %}